// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: unitygameengine.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoUnityGameEngine {

  /// <summary>Holder for reflection information generated from unitygameengine.proto</summary>
  public static partial class UnitygameengineReflection {

    #region Descriptor
    /// <summary>File descriptor for unitygameengine.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnitygameengineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChV1bml0eWdhbWVlbmdpbmUucHJvdG8SC2dycGNfc2VydmVyIj0KHUluR2Ft",
            "ZURhdGFSZWxpYWJsZVJlY2VpdmVkTXNnEg4KBnVzZXJJZBgBIAEoCRIMCgRk",
            "YXRhGAIgASgMIj8KH0luR2FtZURhdGFVbnJlbGlhYmxlUmVjZWl2ZWRNc2cS",
            "DgoGdXNlcklkGAEgASgJEgwKBGRhdGEYAiABKAwiJAoSUGxheWVyQ29ubmVj",
            "dGVkTXNnEg4KBnVzZXJJZBgBIAEoCSInChVQbGF5ZXJEaXNjb25uZWN0ZWRN",
            "c2cSDgoGdXNlcklkGAEgASgJIs0JChNJbml0aWFsTWF0Y2hEYXRhTXNnEkMK",
            "EGluaXRpYWxNYXRjaERhdGEYASADKAsyKS5ncnBjX3NlcnZlci5Jbml0aWFs",
            "TWF0Y2hEYXRhTXNnLlVzZXJEYXRhEhQKB21hdGNoSWQYAiABKAlIAIgBARIW",
            "CglxdWV1ZU5hbWUYAyABKAlIAYgBARIXCgpyZWdpb25OYW1lGAQgASgJSAKI",
            "AQESTgoPY3VzdG9tUm9vbURhdGFzGAUgAygLMjUuZ3JwY19zZXJ2ZXIuSW5p",
            "dGlhbE1hdGNoRGF0YU1zZy5DdXN0b21Sb29tRGF0YXNFbnRyeRJaChVjdXN0",
            "b21NYXRjaG1ha2luZ0RhdGEYBiADKAsyOy5ncnBjX3NlcnZlci5Jbml0aWFs",
            "TWF0Y2hEYXRhTXNnLkN1c3RvbU1hdGNobWFraW5nRGF0YUVudHJ5Eh0KEGV4",
            "dGVybmFsR2FtZURhdGEYByABKAxIA4gBARrSAwoIVXNlckRhdGESDgoGdXNl",
            "cklkGAEgASgJEg0KBWlzQm90GAIgASgIEhUKDWJvdERpZmZpY3VsdHkYAyAB",
            "KAESFgoObWF0Y2htYWtlckRhdGEYBCADKAISFgoOZ2FtZUVuZ2luZURhdGEY",
            "BSABKAwSEwoGcm9vbUlkGAYgASgJSACIAQESFgoJdGVhbUluZGV4GAcgASgN",
            "SAGIAQESFwoKdGVsZWdyYW1JZBgIIAEoCUgCiAEBEhQKB2FkZHJlc3MYCSAB",
            "KAlIA4gBARIVCghuaWNrbmFtZRgKIAEoCUgEiAEBEhkKDG5pY2tuYW1lVHlw",
            "ZRgLIAEoCUgFiAEBEk0KCmN1c3RvbURhdGEYDCADKAsyOS5ncnBjX3NlcnZl",
            "ci5Jbml0aWFsTWF0Y2hEYXRhTXNnLlVzZXJEYXRhLkN1c3RvbURhdGFFbnRy",
            "eRoxCg9DdXN0b21EYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIg",
            "ASgJOgI4AUIJCgdfcm9vbUlkQgwKCl90ZWFtSW5kZXhCDQoLX3RlbGVncmFt",
            "SWRCCgoIX2FkZHJlc3NCCwoJX25pY2tuYW1lQg8KDV9uaWNrbmFtZVR5cGUa",
            "pAEKDkN1c3RvbVJvb21EYXRhElsKDmN1c3RvbVJvb21EYXRhGAEgAygLMkMu",
            "Z3JwY19zZXJ2ZXIuSW5pdGlhbE1hdGNoRGF0YU1zZy5DdXN0b21Sb29tRGF0",
            "YS5DdXN0b21Sb29tRGF0YUVudHJ5GjUKE0N1c3RvbVJvb21EYXRhRW50cnkS",
            "CwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ARpnChRDdXN0b21Sb29t",
            "RGF0YXNFbnRyeRILCgNrZXkYASABKAkSPgoFdmFsdWUYAiABKAsyLy5ncnBj",
            "X3NlcnZlci5Jbml0aWFsTWF0Y2hEYXRhTXNnLkN1c3RvbVJvb21EYXRhOgI4",
            "ARo8ChpDdXN0b21NYXRjaG1ha2luZ0RhdGFFbnRyeRILCgNrZXkYASABKAkS",
            "DQoFdmFsdWUYAiABKAk6AjgBQgoKCF9tYXRjaElkQgwKCl9xdWV1ZU5hbWVC",
            "DQoLX3JlZ2lvbk5hbWVCEwoRX2V4dGVybmFsR2FtZURhdGEiFwoHVGlja01z",
            "ZxIMCgR0aWNrGAEgASgDQheqAhRQcm90b1VuaXR5R2FtZUVuZ2luZWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoUnityGameEngine.InGameDataReliableReceivedMsg), global::ProtoUnityGameEngine.InGameDataReliableReceivedMsg.Parser, new[]{ "UserId", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoUnityGameEngine.InGameDataUnreliableReceivedMsg), global::ProtoUnityGameEngine.InGameDataUnreliableReceivedMsg.Parser, new[]{ "UserId", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoUnityGameEngine.PlayerConnectedMsg), global::ProtoUnityGameEngine.PlayerConnectedMsg.Parser, new[]{ "UserId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoUnityGameEngine.PlayerDisconnectedMsg), global::ProtoUnityGameEngine.PlayerDisconnectedMsg.Parser, new[]{ "UserId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoUnityGameEngine.InitialMatchDataMsg), global::ProtoUnityGameEngine.InitialMatchDataMsg.Parser, new[]{ "InitialMatchData", "MatchId", "QueueName", "RegionName", "CustomRoomDatas", "CustomMatchmakingData", "ExternalGameData" }, new[]{ "MatchId", "QueueName", "RegionName", "ExternalGameData" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.UserData), global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.UserData.Parser, new[]{ "UserId", "IsBot", "BotDifficulty", "MatchmakerData", "GameEngineData", "RoomId", "TeamIndex", "TelegramId", "Address", "Nickname", "NicknameType", "CustomData" }, new[]{ "RoomId", "TeamIndex", "TelegramId", "Address", "Nickname", "NicknameType" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.CustomRoomData), global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.CustomRoomData.Parser, new[]{ "CustomRoomData_" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoUnityGameEngine.TickMsg), global::ProtoUnityGameEngine.TickMsg.Parser, new[]{ "Tick" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class InGameDataReliableReceivedMsg : pb::IMessage<InGameDataReliableReceivedMsg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InGameDataReliableReceivedMsg> _parser = new pb::MessageParser<InGameDataReliableReceivedMsg>(() => new InGameDataReliableReceivedMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InGameDataReliableReceivedMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoUnityGameEngine.UnitygameengineReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InGameDataReliableReceivedMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InGameDataReliableReceivedMsg(InGameDataReliableReceivedMsg other) : this() {
      userId_ = other.userId_;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InGameDataReliableReceivedMsg Clone() {
      return new InGameDataReliableReceivedMsg(this);
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 1;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InGameDataReliableReceivedMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InGameDataReliableReceivedMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InGameDataReliableReceivedMsg other) {
      if (other == null) {
        return;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 18: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 18: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class InGameDataUnreliableReceivedMsg : pb::IMessage<InGameDataUnreliableReceivedMsg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InGameDataUnreliableReceivedMsg> _parser = new pb::MessageParser<InGameDataUnreliableReceivedMsg>(() => new InGameDataUnreliableReceivedMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InGameDataUnreliableReceivedMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoUnityGameEngine.UnitygameengineReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InGameDataUnreliableReceivedMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InGameDataUnreliableReceivedMsg(InGameDataUnreliableReceivedMsg other) : this() {
      userId_ = other.userId_;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InGameDataUnreliableReceivedMsg Clone() {
      return new InGameDataUnreliableReceivedMsg(this);
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 1;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InGameDataUnreliableReceivedMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InGameDataUnreliableReceivedMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InGameDataUnreliableReceivedMsg other) {
      if (other == null) {
        return;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 18: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 18: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerConnectedMsg : pb::IMessage<PlayerConnectedMsg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerConnectedMsg> _parser = new pb::MessageParser<PlayerConnectedMsg>(() => new PlayerConnectedMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerConnectedMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoUnityGameEngine.UnitygameengineReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerConnectedMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerConnectedMsg(PlayerConnectedMsg other) : this() {
      userId_ = other.userId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerConnectedMsg Clone() {
      return new PlayerConnectedMsg(this);
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 1;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerConnectedMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerConnectedMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerConnectedMsg other) {
      if (other == null) {
        return;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerDisconnectedMsg : pb::IMessage<PlayerDisconnectedMsg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerDisconnectedMsg> _parser = new pb::MessageParser<PlayerDisconnectedMsg>(() => new PlayerDisconnectedMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerDisconnectedMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoUnityGameEngine.UnitygameengineReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerDisconnectedMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerDisconnectedMsg(PlayerDisconnectedMsg other) : this() {
      userId_ = other.userId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerDisconnectedMsg Clone() {
      return new PlayerDisconnectedMsg(this);
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 1;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerDisconnectedMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerDisconnectedMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerDisconnectedMsg other) {
      if (other == null) {
        return;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class InitialMatchDataMsg : pb::IMessage<InitialMatchDataMsg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InitialMatchDataMsg> _parser = new pb::MessageParser<InitialMatchDataMsg>(() => new InitialMatchDataMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InitialMatchDataMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoUnityGameEngine.UnitygameengineReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitialMatchDataMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitialMatchDataMsg(InitialMatchDataMsg other) : this() {
      initialMatchData_ = other.initialMatchData_.Clone();
      matchId_ = other.matchId_;
      queueName_ = other.queueName_;
      regionName_ = other.regionName_;
      customRoomDatas_ = other.customRoomDatas_.Clone();
      customMatchmakingData_ = other.customMatchmakingData_.Clone();
      externalGameData_ = other.externalGameData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitialMatchDataMsg Clone() {
      return new InitialMatchDataMsg(this);
    }

    /// <summary>Field number for the "initialMatchData" field.</summary>
    public const int InitialMatchDataFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.UserData> _repeated_initialMatchData_codec
        = pb::FieldCodec.ForMessage(10, global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.UserData.Parser);
    private readonly pbc::RepeatedField<global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.UserData> initialMatchData_ = new pbc::RepeatedField<global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.UserData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.UserData> InitialMatchData {
      get { return initialMatchData_; }
    }

    /// <summary>Field number for the "matchId" field.</summary>
    public const int MatchIdFieldNumber = 2;
    private readonly static string MatchIdDefaultValue = "";

    private string matchId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MatchId {
      get { return matchId_ ?? MatchIdDefaultValue; }
      set {
        matchId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "matchId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMatchId {
      get { return matchId_ != null; }
    }
    /// <summary>Clears the value of the "matchId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMatchId() {
      matchId_ = null;
    }

    /// <summary>Field number for the "queueName" field.</summary>
    public const int QueueNameFieldNumber = 3;
    private readonly static string QueueNameDefaultValue = "";

    private string queueName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string QueueName {
      get { return queueName_ ?? QueueNameDefaultValue; }
      set {
        queueName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "queueName" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasQueueName {
      get { return queueName_ != null; }
    }
    /// <summary>Clears the value of the "queueName" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearQueueName() {
      queueName_ = null;
    }

    /// <summary>Field number for the "regionName" field.</summary>
    public const int RegionNameFieldNumber = 4;
    private readonly static string RegionNameDefaultValue = "";

    private string regionName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RegionName {
      get { return regionName_ ?? RegionNameDefaultValue; }
      set {
        regionName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "regionName" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRegionName {
      get { return regionName_ != null; }
    }
    /// <summary>Clears the value of the "regionName" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRegionName() {
      regionName_ = null;
    }

    /// <summary>Field number for the "customRoomDatas" field.</summary>
    public const int CustomRoomDatasFieldNumber = 5;
    private static readonly pbc::MapField<string, global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.CustomRoomData>.Codec _map_customRoomDatas_codec
        = new pbc::MapField<string, global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.CustomRoomData>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.CustomRoomData.Parser), 42);
    private readonly pbc::MapField<string, global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.CustomRoomData> customRoomDatas_ = new pbc::MapField<string, global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.CustomRoomData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::ProtoUnityGameEngine.InitialMatchDataMsg.Types.CustomRoomData> CustomRoomDatas {
      get { return customRoomDatas_; }
    }

    /// <summary>Field number for the "customMatchmakingData" field.</summary>
    public const int CustomMatchmakingDataFieldNumber = 6;
    private static readonly pbc::MapField<string, string>.Codec _map_customMatchmakingData_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 50);
    private readonly pbc::MapField<string, string> customMatchmakingData_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> CustomMatchmakingData {
      get { return customMatchmakingData_; }
    }

    /// <summary>Field number for the "externalGameData" field.</summary>
    public const int ExternalGameDataFieldNumber = 7;
    private readonly static pb::ByteString ExternalGameDataDefaultValue = pb::ByteString.Empty;

    private pb::ByteString externalGameData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ExternalGameData {
      get { return externalGameData_ ?? ExternalGameDataDefaultValue; }
      set {
        externalGameData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "externalGameData" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasExternalGameData {
      get { return externalGameData_ != null; }
    }
    /// <summary>Clears the value of the "externalGameData" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearExternalGameData() {
      externalGameData_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InitialMatchDataMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InitialMatchDataMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!initialMatchData_.Equals(other.initialMatchData_)) return false;
      if (MatchId != other.MatchId) return false;
      if (QueueName != other.QueueName) return false;
      if (RegionName != other.RegionName) return false;
      if (!CustomRoomDatas.Equals(other.CustomRoomDatas)) return false;
      if (!CustomMatchmakingData.Equals(other.CustomMatchmakingData)) return false;
      if (ExternalGameData != other.ExternalGameData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= initialMatchData_.GetHashCode();
      if (HasMatchId) hash ^= MatchId.GetHashCode();
      if (HasQueueName) hash ^= QueueName.GetHashCode();
      if (HasRegionName) hash ^= RegionName.GetHashCode();
      hash ^= CustomRoomDatas.GetHashCode();
      hash ^= CustomMatchmakingData.GetHashCode();
      if (HasExternalGameData) hash ^= ExternalGameData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      initialMatchData_.WriteTo(output, _repeated_initialMatchData_codec);
      if (HasMatchId) {
        output.WriteRawTag(18);
        output.WriteString(MatchId);
      }
      if (HasQueueName) {
        output.WriteRawTag(26);
        output.WriteString(QueueName);
      }
      if (HasRegionName) {
        output.WriteRawTag(34);
        output.WriteString(RegionName);
      }
      customRoomDatas_.WriteTo(output, _map_customRoomDatas_codec);
      customMatchmakingData_.WriteTo(output, _map_customMatchmakingData_codec);
      if (HasExternalGameData) {
        output.WriteRawTag(58);
        output.WriteBytes(ExternalGameData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      initialMatchData_.WriteTo(ref output, _repeated_initialMatchData_codec);
      if (HasMatchId) {
        output.WriteRawTag(18);
        output.WriteString(MatchId);
      }
      if (HasQueueName) {
        output.WriteRawTag(26);
        output.WriteString(QueueName);
      }
      if (HasRegionName) {
        output.WriteRawTag(34);
        output.WriteString(RegionName);
      }
      customRoomDatas_.WriteTo(ref output, _map_customRoomDatas_codec);
      customMatchmakingData_.WriteTo(ref output, _map_customMatchmakingData_codec);
      if (HasExternalGameData) {
        output.WriteRawTag(58);
        output.WriteBytes(ExternalGameData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += initialMatchData_.CalculateSize(_repeated_initialMatchData_codec);
      if (HasMatchId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MatchId);
      }
      if (HasQueueName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(QueueName);
      }
      if (HasRegionName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RegionName);
      }
      size += customRoomDatas_.CalculateSize(_map_customRoomDatas_codec);
      size += customMatchmakingData_.CalculateSize(_map_customMatchmakingData_codec);
      if (HasExternalGameData) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ExternalGameData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InitialMatchDataMsg other) {
      if (other == null) {
        return;
      }
      initialMatchData_.Add(other.initialMatchData_);
      if (other.HasMatchId) {
        MatchId = other.MatchId;
      }
      if (other.HasQueueName) {
        QueueName = other.QueueName;
      }
      if (other.HasRegionName) {
        RegionName = other.RegionName;
      }
      customRoomDatas_.MergeFrom(other.customRoomDatas_);
      customMatchmakingData_.MergeFrom(other.customMatchmakingData_);
      if (other.HasExternalGameData) {
        ExternalGameData = other.ExternalGameData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            initialMatchData_.AddEntriesFrom(input, _repeated_initialMatchData_codec);
            break;
          }
          case 18: {
            MatchId = input.ReadString();
            break;
          }
          case 26: {
            QueueName = input.ReadString();
            break;
          }
          case 34: {
            RegionName = input.ReadString();
            break;
          }
          case 42: {
            customRoomDatas_.AddEntriesFrom(input, _map_customRoomDatas_codec);
            break;
          }
          case 50: {
            customMatchmakingData_.AddEntriesFrom(input, _map_customMatchmakingData_codec);
            break;
          }
          case 58: {
            ExternalGameData = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            initialMatchData_.AddEntriesFrom(ref input, _repeated_initialMatchData_codec);
            break;
          }
          case 18: {
            MatchId = input.ReadString();
            break;
          }
          case 26: {
            QueueName = input.ReadString();
            break;
          }
          case 34: {
            RegionName = input.ReadString();
            break;
          }
          case 42: {
            customRoomDatas_.AddEntriesFrom(ref input, _map_customRoomDatas_codec);
            break;
          }
          case 50: {
            customMatchmakingData_.AddEntriesFrom(ref input, _map_customMatchmakingData_codec);
            break;
          }
          case 58: {
            ExternalGameData = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the InitialMatchDataMsg message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class UserData : pb::IMessage<UserData>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<UserData> _parser = new pb::MessageParser<UserData>(() => new UserData());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<UserData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ProtoUnityGameEngine.InitialMatchDataMsg.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public UserData() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public UserData(UserData other) : this() {
          _hasBits0 = other._hasBits0;
          userId_ = other.userId_;
          isBot_ = other.isBot_;
          botDifficulty_ = other.botDifficulty_;
          matchmakerData_ = other.matchmakerData_.Clone();
          gameEngineData_ = other.gameEngineData_;
          roomId_ = other.roomId_;
          teamIndex_ = other.teamIndex_;
          telegramId_ = other.telegramId_;
          address_ = other.address_;
          nickname_ = other.nickname_;
          nicknameType_ = other.nicknameType_;
          customData_ = other.customData_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public UserData Clone() {
          return new UserData(this);
        }

        /// <summary>Field number for the "userId" field.</summary>
        public const int UserIdFieldNumber = 1;
        private string userId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string UserId {
          get { return userId_; }
          set {
            userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "isBot" field.</summary>
        public const int IsBotFieldNumber = 2;
        private bool isBot_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool IsBot {
          get { return isBot_; }
          set {
            isBot_ = value;
          }
        }

        /// <summary>Field number for the "botDifficulty" field.</summary>
        public const int BotDifficultyFieldNumber = 3;
        private double botDifficulty_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double BotDifficulty {
          get { return botDifficulty_; }
          set {
            botDifficulty_ = value;
          }
        }

        /// <summary>Field number for the "matchmakerData" field.</summary>
        public const int MatchmakerDataFieldNumber = 4;
        private static readonly pb::FieldCodec<float> _repeated_matchmakerData_codec
            = pb::FieldCodec.ForFloat(34);
        private readonly pbc::RepeatedField<float> matchmakerData_ = new pbc::RepeatedField<float>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<float> MatchmakerData {
          get { return matchmakerData_; }
        }

        /// <summary>Field number for the "gameEngineData" field.</summary>
        public const int GameEngineDataFieldNumber = 5;
        private pb::ByteString gameEngineData_ = pb::ByteString.Empty;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString GameEngineData {
          get { return gameEngineData_; }
          set {
            gameEngineData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "roomId" field.</summary>
        public const int RoomIdFieldNumber = 6;
        private readonly static string RoomIdDefaultValue = "";

        private string roomId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string RoomId {
          get { return roomId_ ?? RoomIdDefaultValue; }
          set {
            roomId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "roomId" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasRoomId {
          get { return roomId_ != null; }
        }
        /// <summary>Clears the value of the "roomId" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearRoomId() {
          roomId_ = null;
        }

        /// <summary>Field number for the "teamIndex" field.</summary>
        public const int TeamIndexFieldNumber = 7;
        private readonly static uint TeamIndexDefaultValue = 0;

        private uint teamIndex_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint TeamIndex {
          get { if ((_hasBits0 & 1) != 0) { return teamIndex_; } else { return TeamIndexDefaultValue; } }
          set {
            _hasBits0 |= 1;
            teamIndex_ = value;
          }
        }
        /// <summary>Gets whether the "teamIndex" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasTeamIndex {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "teamIndex" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearTeamIndex() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "telegramId" field.</summary>
        public const int TelegramIdFieldNumber = 8;
        private readonly static string TelegramIdDefaultValue = "";

        private string telegramId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string TelegramId {
          get { return telegramId_ ?? TelegramIdDefaultValue; }
          set {
            telegramId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "telegramId" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasTelegramId {
          get { return telegramId_ != null; }
        }
        /// <summary>Clears the value of the "telegramId" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearTelegramId() {
          telegramId_ = null;
        }

        /// <summary>Field number for the "address" field.</summary>
        public const int AddressFieldNumber = 9;
        private readonly static string AddressDefaultValue = "";

        private string address_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Address {
          get { return address_ ?? AddressDefaultValue; }
          set {
            address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "address" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasAddress {
          get { return address_ != null; }
        }
        /// <summary>Clears the value of the "address" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearAddress() {
          address_ = null;
        }

        /// <summary>Field number for the "nickname" field.</summary>
        public const int NicknameFieldNumber = 10;
        private readonly static string NicknameDefaultValue = "";

        private string nickname_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Nickname {
          get { return nickname_ ?? NicknameDefaultValue; }
          set {
            nickname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "nickname" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasNickname {
          get { return nickname_ != null; }
        }
        /// <summary>Clears the value of the "nickname" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearNickname() {
          nickname_ = null;
        }

        /// <summary>Field number for the "nicknameType" field.</summary>
        public const int NicknameTypeFieldNumber = 11;
        private readonly static string NicknameTypeDefaultValue = "";

        private string nicknameType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string NicknameType {
          get { return nicknameType_ ?? NicknameTypeDefaultValue; }
          set {
            nicknameType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "nicknameType" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasNicknameType {
          get { return nicknameType_ != null; }
        }
        /// <summary>Clears the value of the "nicknameType" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearNicknameType() {
          nicknameType_ = null;
        }

        /// <summary>Field number for the "customData" field.</summary>
        public const int CustomDataFieldNumber = 12;
        private static readonly pbc::MapField<string, string>.Codec _map_customData_codec
            = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 98);
        private readonly pbc::MapField<string, string> customData_ = new pbc::MapField<string, string>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::MapField<string, string> CustomData {
          get { return customData_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as UserData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(UserData other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (UserId != other.UserId) return false;
          if (IsBot != other.IsBot) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(BotDifficulty, other.BotDifficulty)) return false;
          if(!matchmakerData_.Equals(other.matchmakerData_)) return false;
          if (GameEngineData != other.GameEngineData) return false;
          if (RoomId != other.RoomId) return false;
          if (TeamIndex != other.TeamIndex) return false;
          if (TelegramId != other.TelegramId) return false;
          if (Address != other.Address) return false;
          if (Nickname != other.Nickname) return false;
          if (NicknameType != other.NicknameType) return false;
          if (!CustomData.Equals(other.CustomData)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (UserId.Length != 0) hash ^= UserId.GetHashCode();
          if (IsBot != false) hash ^= IsBot.GetHashCode();
          if (BotDifficulty != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(BotDifficulty);
          hash ^= matchmakerData_.GetHashCode();
          if (GameEngineData.Length != 0) hash ^= GameEngineData.GetHashCode();
          if (HasRoomId) hash ^= RoomId.GetHashCode();
          if (HasTeamIndex) hash ^= TeamIndex.GetHashCode();
          if (HasTelegramId) hash ^= TelegramId.GetHashCode();
          if (HasAddress) hash ^= Address.GetHashCode();
          if (HasNickname) hash ^= Nickname.GetHashCode();
          if (HasNicknameType) hash ^= NicknameType.GetHashCode();
          hash ^= CustomData.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (UserId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(UserId);
          }
          if (IsBot != false) {
            output.WriteRawTag(16);
            output.WriteBool(IsBot);
          }
          if (BotDifficulty != 0D) {
            output.WriteRawTag(25);
            output.WriteDouble(BotDifficulty);
          }
          matchmakerData_.WriteTo(output, _repeated_matchmakerData_codec);
          if (GameEngineData.Length != 0) {
            output.WriteRawTag(42);
            output.WriteBytes(GameEngineData);
          }
          if (HasRoomId) {
            output.WriteRawTag(50);
            output.WriteString(RoomId);
          }
          if (HasTeamIndex) {
            output.WriteRawTag(56);
            output.WriteUInt32(TeamIndex);
          }
          if (HasTelegramId) {
            output.WriteRawTag(66);
            output.WriteString(TelegramId);
          }
          if (HasAddress) {
            output.WriteRawTag(74);
            output.WriteString(Address);
          }
          if (HasNickname) {
            output.WriteRawTag(82);
            output.WriteString(Nickname);
          }
          if (HasNicknameType) {
            output.WriteRawTag(90);
            output.WriteString(NicknameType);
          }
          customData_.WriteTo(output, _map_customData_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (UserId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(UserId);
          }
          if (IsBot != false) {
            output.WriteRawTag(16);
            output.WriteBool(IsBot);
          }
          if (BotDifficulty != 0D) {
            output.WriteRawTag(25);
            output.WriteDouble(BotDifficulty);
          }
          matchmakerData_.WriteTo(ref output, _repeated_matchmakerData_codec);
          if (GameEngineData.Length != 0) {
            output.WriteRawTag(42);
            output.WriteBytes(GameEngineData);
          }
          if (HasRoomId) {
            output.WriteRawTag(50);
            output.WriteString(RoomId);
          }
          if (HasTeamIndex) {
            output.WriteRawTag(56);
            output.WriteUInt32(TeamIndex);
          }
          if (HasTelegramId) {
            output.WriteRawTag(66);
            output.WriteString(TelegramId);
          }
          if (HasAddress) {
            output.WriteRawTag(74);
            output.WriteString(Address);
          }
          if (HasNickname) {
            output.WriteRawTag(82);
            output.WriteString(Nickname);
          }
          if (HasNicknameType) {
            output.WriteRawTag(90);
            output.WriteString(NicknameType);
          }
          customData_.WriteTo(ref output, _map_customData_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (UserId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
          }
          if (IsBot != false) {
            size += 1 + 1;
          }
          if (BotDifficulty != 0D) {
            size += 1 + 8;
          }
          size += matchmakerData_.CalculateSize(_repeated_matchmakerData_codec);
          if (GameEngineData.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(GameEngineData);
          }
          if (HasRoomId) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomId);
          }
          if (HasTeamIndex) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TeamIndex);
          }
          if (HasTelegramId) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(TelegramId);
          }
          if (HasAddress) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Address);
          }
          if (HasNickname) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Nickname);
          }
          if (HasNicknameType) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(NicknameType);
          }
          size += customData_.CalculateSize(_map_customData_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(UserData other) {
          if (other == null) {
            return;
          }
          if (other.UserId.Length != 0) {
            UserId = other.UserId;
          }
          if (other.IsBot != false) {
            IsBot = other.IsBot;
          }
          if (other.BotDifficulty != 0D) {
            BotDifficulty = other.BotDifficulty;
          }
          matchmakerData_.Add(other.matchmakerData_);
          if (other.GameEngineData.Length != 0) {
            GameEngineData = other.GameEngineData;
          }
          if (other.HasRoomId) {
            RoomId = other.RoomId;
          }
          if (other.HasTeamIndex) {
            TeamIndex = other.TeamIndex;
          }
          if (other.HasTelegramId) {
            TelegramId = other.TelegramId;
          }
          if (other.HasAddress) {
            Address = other.Address;
          }
          if (other.HasNickname) {
            Nickname = other.Nickname;
          }
          if (other.HasNicknameType) {
            NicknameType = other.NicknameType;
          }
          customData_.MergeFrom(other.customData_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                UserId = input.ReadString();
                break;
              }
              case 16: {
                IsBot = input.ReadBool();
                break;
              }
              case 25: {
                BotDifficulty = input.ReadDouble();
                break;
              }
              case 34:
              case 37: {
                matchmakerData_.AddEntriesFrom(input, _repeated_matchmakerData_codec);
                break;
              }
              case 42: {
                GameEngineData = input.ReadBytes();
                break;
              }
              case 50: {
                RoomId = input.ReadString();
                break;
              }
              case 56: {
                TeamIndex = input.ReadUInt32();
                break;
              }
              case 66: {
                TelegramId = input.ReadString();
                break;
              }
              case 74: {
                Address = input.ReadString();
                break;
              }
              case 82: {
                Nickname = input.ReadString();
                break;
              }
              case 90: {
                NicknameType = input.ReadString();
                break;
              }
              case 98: {
                customData_.AddEntriesFrom(input, _map_customData_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                UserId = input.ReadString();
                break;
              }
              case 16: {
                IsBot = input.ReadBool();
                break;
              }
              case 25: {
                BotDifficulty = input.ReadDouble();
                break;
              }
              case 34:
              case 37: {
                matchmakerData_.AddEntriesFrom(ref input, _repeated_matchmakerData_codec);
                break;
              }
              case 42: {
                GameEngineData = input.ReadBytes();
                break;
              }
              case 50: {
                RoomId = input.ReadString();
                break;
              }
              case 56: {
                TeamIndex = input.ReadUInt32();
                break;
              }
              case 66: {
                TelegramId = input.ReadString();
                break;
              }
              case 74: {
                Address = input.ReadString();
                break;
              }
              case 82: {
                Nickname = input.ReadString();
                break;
              }
              case 90: {
                NicknameType = input.ReadString();
                break;
              }
              case 98: {
                customData_.AddEntriesFrom(ref input, _map_customData_codec);
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class CustomRoomData : pb::IMessage<CustomRoomData>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<CustomRoomData> _parser = new pb::MessageParser<CustomRoomData>(() => new CustomRoomData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CustomRoomData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ProtoUnityGameEngine.InitialMatchDataMsg.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CustomRoomData() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CustomRoomData(CustomRoomData other) : this() {
          customRoomData_ = other.customRoomData_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CustomRoomData Clone() {
          return new CustomRoomData(this);
        }

        /// <summary>Field number for the "customRoomData" field.</summary>
        public const int CustomRoomData_FieldNumber = 1;
        private static readonly pbc::MapField<string, string>.Codec _map_customRoomData_codec
            = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 10);
        private readonly pbc::MapField<string, string> customRoomData_ = new pbc::MapField<string, string>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::MapField<string, string> CustomRoomData_ {
          get { return customRoomData_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as CustomRoomData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CustomRoomData other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!CustomRoomData_.Equals(other.CustomRoomData_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= CustomRoomData_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          customRoomData_.WriteTo(output, _map_customRoomData_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          customRoomData_.WriteTo(ref output, _map_customRoomData_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          size += customRoomData_.CalculateSize(_map_customRoomData_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CustomRoomData other) {
          if (other == null) {
            return;
          }
          customRoomData_.MergeFrom(other.customRoomData_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                customRoomData_.AddEntriesFrom(input, _map_customRoomData_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                customRoomData_.AddEntriesFrom(ref input, _map_customRoomData_codec);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TickMsg : pb::IMessage<TickMsg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TickMsg> _parser = new pb::MessageParser<TickMsg>(() => new TickMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TickMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoUnityGameEngine.UnitygameengineReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TickMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TickMsg(TickMsg other) : this() {
      tick_ = other.tick_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TickMsg Clone() {
      return new TickMsg(this);
    }

    /// <summary>Field number for the "tick" field.</summary>
    public const int TickFieldNumber = 1;
    private long tick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Tick {
      get { return tick_; }
      set {
        tick_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TickMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TickMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Tick != other.Tick) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Tick != 0L) hash ^= Tick.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Tick != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Tick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Tick != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Tick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Tick != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Tick);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TickMsg other) {
      if (other == null) {
        return;
      }
      if (other.Tick != 0L) {
        Tick = other.Tick;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Tick = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Tick = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
